# Strict build settings
strictDepBuilds: true

# Control script permissions explicitly
allowBuilds:
  esbuild: true
  core-js: false # Explicitly deny core-js if its postinstall script is not needed

# Block untrusted transitive links
blockExoticSubdeps: true

# Enforce a bake period in minutes (1440 * 3 mins = 3 days)
minimumReleaseAge: 4320

# Strictly fail the installation if a package is too new
# If false, pnpm tries to gracefully roll back to the last safe, older version instead
minimumReleaseAgeStrict: true

# Security
ignoreScripts: true

# Fail on peer dependency mismatches
strictPeerDependencies: true

# Fail on invalid SSL/TLS certificates
strictSsl: true
